-- 60 livros para uso na aplicação (diversas categorias e gêneros)
-- IDs gerados em sequência 1..60 (identity). Inventário referenciará id_livro 1..60.
INSERT INTO tb_livro (titulo, autor, categoria, genero, descricao, isbn, ano_publicacao, ativo, data_criacao, data_atualizacao) VALUES
('1984', 'George Orwell', 'Ficção Científica', 'Distopia', 'Romance distópico sobre totalitarismo e vigilância.', '978-8525402136', 1949, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Senhor dos Anéis', 'J.R.R. Tolkien', 'Fantasia', 'Fantasia Épica', 'Trilogia épica na Terra-média.', '978-8533613379', 1954, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dom Quixote', 'Miguel de Cervantes', 'Romance', 'Romance Clássico', 'As aventuras do cavaleiro da triste figura.', '978-8525405014', 1605, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cem Anos de Solidão', 'Gabriel García Márquez', 'Ficção', 'Realismo Mágico', 'Saga da família Buendía em Macondo.', '978-8528610761', 1967, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'Fantasia', 'Fantasia Infantojuvenil', 'O início da saga do jovem bruxo.', '978-8532511010', 1997, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'Infantil', 'Fábula', 'O principezinho que viaja por planetas.', '978-8595081512', 1943, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Orgulho e Preconceito', 'Jane Austen', 'Romance', 'Romance Histórico', 'Elizabeth Bennet e Mr. Darcy na Inglaterra rural.', '978-8525403478', 1813, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Hobbit', 'J.R.R. Tolkien', 'Fantasia', 'Fantasia Épica', 'Bilbo Bolseiro e a jornada até a Montanha Solitária.', '978-8533613492', 1937, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Duna', 'Frank Herbert', 'Ficção Científica', 'Space Opera', 'Arrakis, especiaria e o messias Paul Atreides.', '978-8576572008', 1965, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Crime e Castigo', 'Fiódor Dostoiévski', 'Romance', 'Romance Psicológico', 'Raskólnikov e o assassinato da velha.', '978-8525405120', 1866, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Nome da Rosa', 'Umberto Eco', 'Romance', 'Romance Histórico', 'Mistério em um mosteiro medieval.', '978-8525405236', 1980, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Apanhador no Campo de Centeio', 'J.D. Salinger', 'Romance', 'Romance de Formação', 'Holden Caulfield em Nova York.', '978-8525405343', 1951, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Guia do Mochileiro das Galáxias', 'Douglas Adams', 'Ficção Científica', 'Comédia de Ficção Científica', 'Arthur Dent e a resposta para a vida, o universo e tudo mais.', '978-8525405450', 1979, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fundação', 'Isaac Asimov', 'Ficção Científica', 'Space Opera', 'O Império Galáctico e a Fundação de Hari Seldon.', '978-8525405567', 1951, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Sol é para Todos', 'Harper Lee', 'Romance', 'Romance Social', 'Atticus Finch e o julgamento no Sul dos EUA.', '978-8525405674', 1960, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Neuromancer', 'William Gibson', 'Ficção Científica', 'Cyberpunk', 'Case e a matriz no futuro da informação.', '978-8525405781', 1984, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Estrangeiro', 'Albert Camus', 'Romance', 'Romance Existencialista', 'Meursault e o absurdo da existência.', '978-8525405898', 1942, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A Revolução dos Bichos', 'George Orwell', 'Ficção', 'Alegoria Política', 'Os animais da granja tomam o poder.', '978-8525405904', 1945, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Grande Gatsby', 'F. Scott Fitzgerald', 'Romance', 'Romance Americano', 'Gatsby e o sonho americano nos anos 20.', '978-8525406011', 1925, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ensaio sobre a Cegueira', 'José Saramago', 'Ficção', 'Romance Alegórico', 'Uma epidemia de cegueira branca.', '978-8525406128', 1995, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Alquimista', 'Paulo Coelho', 'Romance', 'Romance de Descoberta', 'O pastor Santiago e sua lenda pessoal.', '978-8525406235', 1988, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Memórias Póstumas de Brás Cubas', 'Machado de Assis', 'Romance', 'Romance Realista', 'Narrador defunto e a sociedade do Rio.', '978-8525406342', 1881, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Retrato de Dorian Gray', 'Oscar Wilde', 'Romance', 'Romance Gótico', 'A beleza, o retrato e a decadência.', '978-8525406459', 1890, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('It - A Coisa', 'Stephen King', 'Terror', 'Terror Sobrenatural', 'O palhaço Pennywise em Derry.', '978-8525406566', 1986, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Iluminado', 'Stephen King', 'Terror', 'Terror Psicológico', 'Jack Torrance e o Overlook Hotel.', '978-8525406673', 1977, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hyperion', 'Dan Simmons', 'Ficção Científica', 'Space Opera', 'Os peregrinos e o Shrike no planeta Hyperion.', '978-8525406780', 1989, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Lobo da Estepe', 'Hermann Hesse', 'Romance', 'Romance Existencialista', 'Harry Haller entre o humano e o lobo.', '978-8525406897', 1927, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sapiens', 'Yuval Noah Harari', 'Não Ficção', 'História', 'Uma breve história da humanidade.', '978-8525406903', 2011, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cosmos', 'Carl Sagan', 'Não Ficção', 'Divulgação Científica', 'Viagem pelo universo e pela ciência.', '978-8525407010', 1980, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Mundo de Sofia', 'Jostein Gaarder', 'Ficção', 'Romance Filosófico', 'Sofia e a história da filosofia.', '978-8525407127', 1991, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A Menina que Roubava Livros', 'Markus Zusak', 'Romance', 'Romance Histórico', 'Liesel na Alemanha nazista.', '978-8525407234', 2005, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Código Da Vinci', 'Dan Brown', 'Suspense', 'Thriller', 'Robert Langdon e o segredo do Graal.', '978-8525407341', 2003, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('As Crônicas de Nárnia', 'C.S. Lewis', 'Fantasia', 'Fantasia Infantojuvenil', 'O guarda-roupa e o mundo de Nárnia.', '978-8525407458', 1950, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Senhor das Moscas', 'William Golding', 'Ficção', 'Romance Alegórico', 'Crianças numa ilha e a queda na selvageria.', '978-8525407565', 1954, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fahrenheit 451', 'Ray Bradbury', 'Ficção Científica', 'Distopia', 'Bombeiros que queimam livros.', '978-8525407672', 1953, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Processo', 'Franz Kafka', 'Romance', 'Romance Existencialista', 'Joseph K. e o processo sem sentido.', '978-8525407789', 1925, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A Metamorfose', 'Franz Kafka', 'Ficção', 'Romance Alegórico', 'Gregor Samsa acorda transformado em inseto.', '978-8525407896', 1915, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Moby Dick', 'Herman Melville', 'Romance', 'Romance de Aventura', 'Capitão Ahab e a caça à baleia branca.', '978-8525407902', 1851, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ulisses', 'James Joyce', 'Romance', 'Romance Modernista', 'Um dia na vida de Leopold Bloom em Dublin.', '978-8525408019', 1922, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A Casa dos Espíritos', 'Isabel Allende', 'Romance', 'Realismo Mágico', 'A família Trueba no Chile.', '978-8525408126', 1982, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Amor nos Tempos do Cólera', 'Gabriel García Márquez', 'Romance', 'Realismo Mágico', 'Florentino e Fermina ao longo das décadas.', '978-8525408233', 1985, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Príncipe', 'Nicolau Maquiavel', 'Não Ficção', 'Ciência Política', 'Reflexões sobre poder e governo.', '978-8525408340', 1532, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Diário de Anne Frank', 'Anne Frank', 'Não Ficção', 'Memórias', 'O diário no esconderijo em Amsterdã.', '978-8525408457', 1947, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sobre a Brevidade da Vida', 'Sêneca', 'Não Ficção', 'Filosofia', 'Cartas sobre o uso do tempo.', '978-8525408564', 49, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Conde de Monte Cristo', 'Alexandre Dumas', 'Romance', 'Romance de Aventura', 'Edmond Dantès e a vingança.', '978-8525408671', 1844, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Os Três Mosqueteiros', 'Alexandre Dumas', 'Romance', 'Romance de Aventura', 'D''Artagnan, Athos, Porthos e Aramis.', '978-8525408788', 1844, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Médico e o Monstro', 'Robert Louis Stevenson', 'Ficção', 'Romance Gótico', 'Dr. Jekyll e Mr. Hyde.', '978-8525408895', 1886, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Drácula', 'Bram Stoker', 'Terror', 'Terror Gótico', 'O conde vampiro na Inglaterra vitoriana.', '978-8525408901', 1897, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Frankenstein', 'Mary Shelley', 'Ficção Científica', 'Terror Gótico', 'Victor Frankenstein e a criatura.', '978-8525409018', 1818, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Silmarillion', 'J.R.R. Tolkien', 'Fantasia', 'Fantasia Épica', 'A criação da Terra-média e as Silmarils.', '978-8525409125', 1977, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Leão, a Feiticeira e o Guarda-Roupa', 'C.S. Lewis', 'Fantasia', 'Fantasia Infantojuvenil', 'Primeiro livro de Nárnia.', '978-8525409232', 1950, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Cemitério', 'Stephen King', 'Terror', 'Terror Sobrenatural', 'Louis Creed e o cemitério dos animais.', '978-8525409349', 1983, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Carrie, a Estranha', 'Stephen King', 'Terror', 'Terror Sobrenatural', 'Carrie White e o baile de formatura.', '978-8525409456', 1974, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Clean Code', 'Robert C. Martin', 'Técnico', 'Programação', 'Arte de código limpo em software.', '978-8535212501', 2008, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Design Patterns', 'Gang of Four', 'Técnico', 'Programação', 'Padrões de projeto orientados a objetos.', '978-8535212502', 1994, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Introdução aos Algoritmos', 'Cormen et al.', 'Técnico', 'Ciência da Computação', 'CLRS: algoritmos e estruturas de dados.', '978-8535212503', 2009, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Canto da Sereia', 'Gillian Flynn', 'Suspense', 'Thriller Psicológico', 'Nick e Amy Dunne e o desaparecimento.', '978-8525409563', 2012, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O Silêncio dos Inocentes', 'Thomas Harris', 'Suspense', 'Thriller Policial', 'Clarice Starling e Hannibal Lecter.', '978-8525409670', 1988, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('And Then There Were None', 'Agatha Christie', 'Policial', 'Mistério', 'Dez estranhos numa ilha.', '978-8525409787', 1939, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Assassinato no Expresso do Oriente', 'Agatha Christie', 'Policial', 'Mistério', 'Poirot no trem e o assassinato.', '978-8525409894', 1934, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
