spring.application.name=rental-service
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/rental_db
spring.datasource.username=rental_user
spring.datasource.password=rental_secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Executa schema.sql e data.sql ao subir
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# RabbitMQ (propagação e consumo do resultado da reserva)
rental.propagation.exchange=rental.topic
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=library_user
spring.rabbitmq.password=library_secret