spring.application.name=search-service
server.port=8083

# Elasticsearch (sempre em container Docker - porta 9200 mapeada para o host)
spring.elasticsearch.uris=http://localhost:9200

# RabbitMQ (catalog.topic + rental.topic para inventory)
catalog.propagation.exchange=catalog.topic
inventory.propagation.exchange=rental.topic
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=library_user
spring.rabbitmq.password=library_secret
